xversion: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  # Root password
      MYSQL_DATABASE: "${MYSQL_DATABASE}"            # Database name
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbFiles/db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql  # Mount your db-setup.sql script
    restart: always

volumes:
  mysql_data:
