version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose the app port
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: "&7yS@X3RzP9#qL2$mW!8ZbF^"
      MYSQL_DATABASE: ecome_db
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Use this to set the root password
      MYSQL_DATABASE: ecome_db
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
